List<String> allPlaces = [
  "Ahrweiler",
  "Aichach-Friedberg",
  "Alb-Donau-Kreis",
  "Altenburger Land",
  "Altenkirchen (Westerwald)",
  "Altmarkkreis Salzwedel",
  "Altötting",
  "Alzey-Worms",
  "Amberg",
  "Amberg-Sulzbach",
  "Ammerland",
  "Anhalt-Bitterfeld",
  "Ansbach",
  "Aschaffenburg",
  "Augsburg",
  "Aurich",
  "Bad Dürkheim",
  "Bad Kissingen",
  "Bad Kreuznach",
  "Bad Tölz-Wolfratshausen",
  "Baden-Baden",
  "Bamberg",
  "Barnim",
  "Bautzen",
  "Bayreuth",
  "Berchtesgadener Land",
  "Bergstraße",
  "Berlin",
  "Bernkastel-Wittlich",
  "Biberach",
  "Bielefeld",
  "Birkenfeld",
  "Bochum",
  "Bodenseekreis",
  "Bonn",
  "Borken",
  "Bottrop",
  "Brandenburg an der Havel",
  "Braunschweig",
  "Breisgau-Hochschwarzwald",
  "Bremen",
  "Bremerhaven",
  "Burgenlandkreis",
  "Böblingen",
  "Börde",
  "Calw",
  "Celle",
  "Cham",
  "Chemnitz",
  "Cloppenburg",
  "Coburg",
  "Cochem-Zell",
  "Coesfeld",
  "Cottbus",
  "Cuxhaven",
  "Dachau",
  "Dahme-Spreewald",
  "Darmstadt",
  "Darmstadt-Dieburg",
  "Deggendorf",
  "Delmenhorst",
  "Dessau-Roßlau",
  "Diepholz",
  "Dillingen a.d. Donau",
  "Dingolfing-Landau",
  "Dithmarschen",
  "Donau-Ries",
  "Donnersbergkreis",
  "Dortmund",
  "Dresden",
  "Duisburg",
  "Düren",
  "Düsseldorf",
  "Ebersberg",
  "Eichsfeld",
  "Eichstätt",
  "Eifelkreis Bitburg-Prüm",
  "Eisenach",
  "Elbe-Elster",
  "Emden",
  "Emmendingen",
  "Emsland",
  "Ennepe-Ruhr-Kreis",
  "Enzkreis",
  "Erding",
  "Erfurt",
  "Erlangen",
  "Erlangen-Höchstadt",
  "Erzgebirgskreis",
  "Essen",
  "Esslingen",
  "Euskirchen",
  "Flensburg",
  "Forchheim",
  "Frankenthal (Pfalz)",
  "Frankfurt (Oder)",
  "Frankfurt am Main",
  "Freiburg im Breisgau",
  "Freising",
  "Freudenstadt",
  "Freyung-Grafenau",
  "Friesland",
  "Fulda",
  "Fürstenfeldbruck",
  "Fürth",
  "Garmisch-Partenkirchen",
  "Gelsenkirchen",
  "Gera",
  "Germersheim",
  "Gießen",
  "Gifhorn",
  "Goslar",
  "Gotha",
  "Grafschaft Bentheim",
  "Greiz",
  "Groß-Gerau",
  "Göppingen",
  "Görlitz",
  "Göttingen",
  "Günzburg",
  "Gütersloh",
  "Hagen",
  "Halle (Saale)",
  "Hamburg",
  "Hameln-Pyrmont",
  "Hamm",
  "Harburg",
  "Harz",
  "Havelland",
  "Haßberge",
  "Heidekreis",
  "Heidelberg",
  "Heidenheim",
  "Heilbronn",
  "Heinsberg",
  "Helmstedt",
  "Herford",
  "Herne",
  "Hersfeld-Rotenburg",
  "Herzogtum Lauenburg",
  "Hildburghausen",
  "Hildesheim",
  "Hochsauerlandkreis",
  "Hochtaunuskreis",
  "Hof",
  "Hohenlohekreis",
  "Holzminden",
  "Höxter",
  "Ilm-Kreis",
  "Ingolstadt",
  "Jena",
  "Jerichower Land",
  "Kaiserslautern",
  "Karlsruhe",
  "Kassel",
  "Kaufbeuren",
  "Kelheim",
  "Kempten (Allgäu)",
  "Kiel",
  "Kitzingen",
  "Kleve",
  "Koblenz",
  "Konstanz",
  "Krefeld",
  "Kronach",
  "Kulmbach",
  "Kusel",
  "Kyffhäuserkreis",
  "Köln",
  "Lahn-Dill-Kreis",
  "Landau in der Pfalz",
  "Landsberg am Lech",
  "Landshut",
  "Leer",
  "Leipzig",
  "Leverkusen",
  "Lichtenfels",
  "Limburg-Weilburg",
  "Lindau (Bodensee)",
  "Lippe",
  "Ludwigsburg",
  "Ludwigshafen am Rhein",
  "Ludwigslust-Parchim",
  "Lörrach",
  "Lübeck",
  "Lüchow-Dannenberg",
  "Lüneburg",
  "Magdeburg",
  "Main-Kinzig-Kreis",
  "Main-Spessart",
  "Main-Tauber-Kreis",
  "Main-Taunus-Kreis",
  "Mainz",
  "Mainz-Bingen",
  "Mannheim",
  "Mansfeld-Südharz",
  "Marburg-Biedenkopf",
  "Mayen-Koblenz",
  "Mecklenburgische Seenplatte",
  "Meißen",
  "Memmingen",
  "Merzig-Wadern",
  "Mettmann",
  "Miesbach",
  "Miltenberg",
  "Minden-Lübbecke",
  "Mittelsachsen",
  "Märkisch-Oderland",
  "Märkischer Kreis",
  "Mönchengladbach",
  "Mühldorf a. Inn",
  "Mülheim an der Ruhr",
  "München",
  "Münster",
  "Neckar-Odenwald-Kreis",
  "Neu-Ulm",
  "Neuburg-Schrobenhausen",
  "Neumarkt i.d. OPf.",
  "Neumünster",
  "Neunkirchen",
  "Neustadt a.d. Aisch-Bad Windsheim",
  "Neustadt a.d. Waldnaab",
  "Neustadt an der Weinstraße",
  "Neuwied",
  "Nienburg (Weser)",
  "Nordfriesland",
  "Nordhausen",
  "Nordsachsen",
  "Nordwestmecklenburg",
  "Northeim",
  "Nürnberg",
  "Nürnberger Land",
  "Oberallgäu",
  "Oberbergischer Kreis",
  "Oberhausen",
  "Oberhavel",
  "Oberspreewald-Lausitz",
  "Odenwaldkreis",
  "Oder-Spree",
  "Offenbach",
  "Offenbach am Main",
  "Oldenburg",
  "Oldenburg (Oldb)",
  "Olpe",
  "Ortenaukreis",
  "Osnabrück",
  "Ostalbkreis",
  "Ostallgäu",
  "Osterholz",
  "Osterode am Harz",
  "Ostholstein",
  "Ostprignitz-Ruppin",
  "Paderborn",
  "Passau",
  "Peine",
  "Pfaffenhofen a.d. Ilm",
  "Pforzheim",
  "Pinneberg",
  "Pirmasens",
  "Plön",
  "Potsdam",
  "Potsdam-Mittelmark",
  "Prignitz",
  "Rastatt",
  "Ravensburg",
  "Recklinghausen",
  "Regen",
  "Regensburg",
  "Region Hannover",
  "Regionalverband Saarbrücken",
  "Rems-Murr-Kreis",
  "Remscheid",
  "Rendsburg-Eckernförde",
  "Reutlingen",
  "Rhein-Erft-Kreis",
  "Rhein-Hunsrück-Kreis",
  "Rhein-Kreis Neuss",
  "Rhein-Lahn-Kreis",
  "Rhein-Neckar-Kreis",
  "Rhein-Pfalz-Kreis",
  "Rhein-Sieg-Kreis",
  "Rheingau-Taunus-Kreis",
  "Rheinisch-Bergischer Kreis",
  "Rhön-Grabfeld",
  "Rosenheim",
  "Rostock",
  "Rotenburg (Wümme)",
  "Roth",
  "Rottal-Inn",
  "Rottweil",
  "Saale-Holzland-Kreis",
  "Saale-Orla-Kreis",
  "Saalekreis",
  "Saalfeld-Rudolstadt",
  "Saarlouis",
  "Saarpfalz-Kreis",
  "Salzgitter",
  "Salzlandkreis",
  "Schaumburg",
  "Schleswig-Flensburg",
  "Schmalkalden-Meiningen",
  "Schwabach",
  "Schwalm-Eder-Kreis",
  "Schwandorf",
  "Schwarzwald-Baar-Kreis",
  "Schweinfurt",
  "Schwerin",
  "Schwäbisch Hall",
  "Segeberg",
  "Siegen-Wittgenstein",
  "Sigmaringen",
  "Soest",
  "Solingen",
  "Sonneberg",
  "Speyer",
  "Spree-Neiße",
  "St. Wendel",
  "Stade",
  "Starnberg",
  "Steinburg",
  "Steinfurt",
  "Stendal",
  "Stormarn",
  "Straubing",
  "Straubing-Bogen",
  "Stuttgart",
  "Städteregion Aachen",
  "Suhl",
  "Sächsische Schweiz-Osterzgebirge",
  "Sömmerda",
  "Südliche Weinstraße",
  "Südwestpfalz",
  "Teltow-Fläming",
  "Tirschenreuth",
  "Traunstein",
  "Trier",
  "Trier-Saarburg",
  "Tuttlingen",
  "Tübingen",
  "Uckermark",
  "Uelzen",
  "Ulm",
  "Unna",
  "Unstrut-Hainich-Kreis",
  "Unterallgäu",
  "Vechta",
  "Verden",
  "Viersen",
  "Vogelsbergkreis",
  "Vogtlandkreis",
  "Vorpommern-Greifswald",
  "Vorpommern-Rügen",
  "Vulkaneifel",
  "Waldeck-Frankenberg",
  "Waldshut",
  "Warendorf",
  "Wartburgkreis",
  "Weiden i.d. OPf.",
  "Weilheim-Schongau",
  "Weimar",
  "Weimarer Land",
  "Weißenburg-Gunzenhausen",
  "Werra-Meißner-Kreis",
  "Wesel",
  "Wesermarsch",
  "Westerwaldkreis",
  "Wetteraukreis",
  "Wiesbaden",
  "Wilhelmshaven",
  "Wittenberg",
  "Wittmund",
  "Wolfenbüttel",
  "Wolfsburg",
  "Worms",
  "Wunsiedel i. Fichtelgebirge",
  "Wuppertal",
  "Würzburg",
  "Zollernalbkreis",
  "Zweibrücken",
  "Zwickau",
];

Map<String, String> alertSwissPlacesMap = new Map();
List<String> alertSwissPlacesList = [
  "ZH",
  "BE",
  "LU",
  "UR",
  "SZ",
  "OW",
  "NW",
  "GL",
  "ZG",
  "FR",
  "SO",
  "BS",
  "BL",
  "SH",
  "AR",
  "AI",
  "SG",
  "GR",
  "AG",
  "TG",
  "TI",
  "VD",
  "VS",
  "NE",
  "GE",
  "JU",
  "CH",
];
